update AppManager.js

diff --git a/codemagic.yaml b/codemagic.yaml
--- a/codemagic.yaml
+++ b/codemagic.yaml
@@ -38,13 +38,14 @@ workflows:
         script: keychain add-certificates
       - name: Increment build number
         script: |
-          #!/bin/bash
           cd $CM_BUILD_DIR/ios
-          LATEST_BUILD_NUMBER=$(app-store-connect get-latest-app-store-build-number "$APP_STORE_APP_ID")
-          NEW_BUILD_NUMBER=$(($LATEST_BUILD_NUMBER + 1))
-          PLIST="$CM_BUILD_DIR/ios/MercuryAutoForum/Info.plist"
-          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $NEW_BUILD_NUMBER" "$PLIST"
-          echo "Updated CFBundleVersion to $NEW_BUILD_NUMBER"
+          LATEST_BUILD_NUMBER=$(app-store-connect get-latest-testflight-build-number "$APP_STORE_APP_ID" || echo 0)
+          if [[ "$LATEST_BUILD_NUMBER" =~ ^[0-9]+$ ]]; then
+            NEW_BUILD_NUMBER=$((LATEST_BUILD_NUMBER + 1))
+            agvtool new-version -all $NEW_BUILD_NUMBER || { echo "Failed to set new build number"; exit 1; }
+          else
+            exit 1
+          fi
       - name: Set up code signing settings in Xcode project
         script: xcode-project use-profiles --warn-only
       - name: Build IPA for distribution
